# Numpy Array数组和矩阵基本运算
<br>引用链接：https://blog.csdn.net/lwplwf/article/details/55506896

## 1.函数库的导入

In [48]:
import numpy as np

## 2.基本运算

In [2]:
import numpy as np
test1 = np.array([[5,10,15],
                [20,25,30],
                [35,40,45]])
test1.sum()

225

In [3]:
test1.max()

45

In [4]:
test1.min()

5

In [7]:
test1.mean()

25.0

### 2.1 矩阵行/列求和

In [8]:
test1.sum(axis=0)

array([60, 75, 90])

In [9]:
test1.sum(axis=1)

array([ 30,  75, 120])

### 2.2 矩阵乘法

In [10]:
import numpy as np
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
             [7,8]])

In [11]:
print(a * b)

[[ 5 12]
 [21 32]]


In [12]:
print(a.dot(b))

[[19 22]
 [43 50]]


In [13]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


### 2.3 元素求平方

In [15]:
a = np.arange(4)
print(a)
print(a ** 2)

[0 1 2 3]
[0 1 4 9]


### 2.4 元素求e的n次幂

In [16]:
import numpy as np

test = np.arange(5)
print(test)

[0 1 2 3 4]


In [17]:
print(np.exp(test))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [18]:
print(np.sqrt(test))

[0.         1.         1.41421356 1.73205081 2.        ]


### 2.5 向下取整

In [19]:
import numpy as np

test = np.floor(10 * np.random.random((3,4)))
print(test)

[[0. 5. 7. 5.]
 [6. 5. 8. 8.]
 [1. 7. 9. 5.]]


In [20]:
print(np.random.random((3,4)))

[[0.02213052 0.34574501 0.10324913 0.70875792]
 [0.97287661 0.35839332 0.59597706 0.41523842]
 [0.68222853 0.01816387 0.25498905 0.98022062]]


### 2.6 平坦化数组

In [21]:
test.ravel()

array([0., 5., 7., 5., 6., 5., 8., 8., 1., 7., 9., 5.])

### 2.7 矩阵转置

In [23]:
test.shape = (6,2)
print(test)

[[0. 5.]
 [7. 5.]
 [6. 5.]
 [8. 8.]
 [1. 7.]
 [9. 5.]]


In [24]:
test.T

array([[0., 7., 6., 8., 1., 9.],
       [5., 5., 5., 8., 7., 5.]])

### 2.8 矩阵拼接

In [25]:
import numpy as np

a = np.floor(10 * np.random.random((2,2)))
b = np.floor(10 * np.random.random((2,2)))

In [30]:
print(a)
print('---')
print(b)
print('---')
print(np.vstack((a,b)))
print('---')
print(np.hstack((a,b)))

[[4. 5.]
 [8. 4.]]
---
[[7. 2.]
 [7. 1.]]
---
[[4. 5.]
 [8. 4.]
 [7. 2.]
 [7. 1.]]
---
[[4. 5. 7. 2.]
 [8. 4. 7. 1.]]


### 2.9 矩阵拼接 - 按列

In [37]:
import numpy as np

a = np.floor(10 * np.random.random((2,12)))
print(a)

[[3. 3. 8. 6. 7. 4. 9. 2. 7. 1. 6. 2.]
 [8. 8. 5. 2. 2. 2. 3. 2. 0. 8. 1. 9.]]


In [38]:
print(np.hsplit(a,3))

[array([[3., 3., 8., 6.],
       [8., 8., 5., 2.]]), array([[7., 4., 9., 2.],
       [2., 2., 3., 2.]]), array([[7., 1., 6., 2.],
       [0., 8., 1., 9.]])]


In [39]:
print(np.hsplit(a,(3,4)))

[array([[3., 3., 8.],
       [8., 8., 5.]]), array([[6.],
       [2.]]), array([[7., 4., 9., 2., 7., 1., 6., 2.],
       [2., 2., 3., 2., 0., 8., 1., 9.]])]


### 2.10 矩阵拼接 - 按行

In [44]:
import numpy as np

a = np.floor(10 * np.random.random((12,2)))
print(a)

[[0. 3.]
 [1. 4.]
 [2. 4.]
 [6. 3.]
 [8. 8.]
 [5. 5.]
 [3. 7.]
 [6. 5.]
 [4. 5.]
 [5. 7.]
 [3. 0.]
 [1. 6.]]


In [45]:
print(np.vsplit(a,3))

[array([[0., 3.],
       [1., 4.],
       [2., 4.],
       [6., 3.]]), array([[8., 8.],
       [5., 5.],
       [3., 7.],
       [6., 5.]]), array([[4., 5.],
       [5., 7.],
       [3., 0.],
       [1., 6.]])]


In [47]:
print(np.vsplit(a,(3,4)))

[array([[0., 3.],
       [1., 4.],
       [2., 4.]]), array([[6., 3.]]), array([[8., 8.],
       [5., 5.],
       [3., 7.],
       [6., 5.],
       [4., 5.],
       [5., 7.],
       [3., 0.],
       [1., 6.]])]


## 3.创建数组：array

In [49]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array((5, 6, 7, 8))
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print (a)
print ('---')
print (b)
print ('---')
print (c)

[1 2 3 4]
---
[5 6 7 8]
---
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


### 3.1 查询数据类型

In [50]:
print(c.dtype)

int64


### 3.2 创建时指定元素类型

In [51]:
import numpy as np
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
b = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]], dtype='str')
print (a)
print ('---')
print (b)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
---
[['1' '2' '3' '4']
 ['4' '5' '6' '7']
 ['7' '8' '9' '10']]


### 3.2 转换数据类型

In [52]:
b = b.astype(int)
print(b)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


### 3.3 array数组的数据类型
<br>bool -- True , False
<br>int -- int16 , int32 , int64
<br>float -- float16 , float32 , float64
<br>string -- string , unicode

### 3.4 查询矩阵大小

In [53]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print (a.shape)
print ('---')
print (b.shape)

(4,)
---
(3, 4)


In [54]:
b.shape = 4,3
print(b)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [55]:
b.shape = 2,-1
print(b)

[[ 1  2  3  4  4  5]
 [ 6  7  7  8  9 10]]


In [59]:
a = np.array((1,2,3,4))
b = a.reshape((2,2))
print(a)
print ('---')
print(b)

[1 2 3 4]
---
[[1 2]
 [3 4]]


### 3.5 复制 =

In [61]:
a[2] = 100
b

array([[  1,   2],
       [100,   4]])

In [62]:
import numpy as np
a = np.arange(12)
b = a

print (a)
print (b)
print (b is a)

b.shape = 3, 4
print (a.shape)

print (id(a))
print (id(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
True
(3, 4)
140163452269152
140163452269152


### 3.6 浅复制 view

In [64]:
import numpy as np
a = np.arange(12)
b = a.view()

print (a is b)
print (b)

b.shape = 2, 6
print (a.shape)
print (b)

b[0, 4] = 1234
print (b)
print (a)

False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[   0    1    2    3 1234    5    6    7    8    9   10   11]


### 3.7 深复制 copy

In [65]:
import numpy as np
a = np.arange(12)
a.shape = 3, 4
a[1, 0] = 1234

c = a.copy()
c is a
c[0, 0] = 9999
print (c)
print (a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


### 3.8 查询纬度 ndim

In [66]:
import numpy as np
a = np.array([[5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])
a.ndim

2

### 3.9 查询元素个数

import numpy as np
a = np.array([[5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])
a.size

### 3.10 创建0矩阵 zeros

In [68]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.zeros((3,4),dtype=np.str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

### 3.11 创建1矩阵 ones

In [70]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 3.11 区间内按等差创建矩阵 arange

In [71]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [72]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [73]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.random.random((2,3))

array([[0.11780853, 0.07199162, 0.824411  ],
       [0.79927113, 0.70098787, 0.04058887]])

### 3.12 区间内按元素个数取值 linspace

In [75]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

### 3.13 利用==判断数组或矩阵中是否存在某个值

In [78]:
import numpy as np
test = np.array([5,10,15,20,25])
test == 15

array([False, False,  True, False, False])

In [79]:
test1 = np.array([[5,10,15],
                 [20,25,30],
                 [35,40,45]]
                )
test1 == 30

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])